theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Wilson Del Canto Cepeda
description: Bienvenido a mi Portfolio
name: &name "Wilson Del Canto Cepeda"
title_separator: "-"
show_downloads: True
locale: "en-ES"
